name: 'cd-front'
run-name: 'cd-front'
on:
  pull_request:
    branches: [ main ]

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:

    - name: checkout
      uses: actions/checkout@v4

    - name: Create cd bucket
      uses: bitovi/github-actions-deploy-static-site-to-aws@v0.1.3
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
        aws_default_region: us-east-1

        tf_action: 'apply'
        tf_state_bucket_destroy: true
        
        aws_spa_cdn_enabled: true
        aws_resource_identifier: '1023c04grupo5front'

        aws_spa_source_folder: 'dist'
